### PR TITLE
Update tree-sitter to 0.23.0

### PR DESCRIPTION
**Pull request by leandrocp**
The title says it all :)

### CODE REVIEW

**Comment by Colonial-Dev** [comment]
Oops, must've missed the e-mail for this - thank you!

Give me a day or two to finish the Helix theme branch and I'll push everything to Crates.

**Comment by leandrocp** [comment]
@Colonial-Dev no problem! take your time.

Are you planning on updating the langs? Otherwise I can go ahead and do it, at least update the "main" ones to include in that release.

**Comment by Colonial-Dev** [comment]
Yep, that's on the checklist. Are you looking for a particular language(s)?

**Comment by leandrocp** [comment]
> Yep, that's on the checklist. Are you looking for a particular language(s)?

Nice. No particular lang on mind, just making sure grammars are updated so colors look correct.

**Pull request merged**
