### PR TITLE
Update languages

### PR DESCRIPTION
**Pull request by leandrocp**
## Haskell

Just regular update.

## Javascript / Typescript

I noticed that both Javascript and Typescript were not highlighting correctly and seems like it's due to not loading the [ecma](https://github.com/helix-editor/helix/tree/master/runtime/queries/ecma) queries.

That's how it looks like loading only the private package: https://autumn-30n.pages.dev/javascript_onedark

And that's how it looks like loading the public package 👇🏻 
Screenshot 2023-10-23 at 11 20 04 AM

### CODE REVIEW

**Comment by Colonial-Dev** [comment]
Nice catch - I really need to get around to writing my own integration tests...

Looks good to me, except for one thing - I wouldn't remove the `hash` keys from the configuration. That's not a Helix thing - it's used to keep the grammar version pinned, so this crate doesn't explode when a new `tree-sitter` version comes out.

(I may need to check the implementation of that though - unless I forgot to run the re-download job after bumping its hash, then the Haskell grammar shouldn't have updated...)

**Comment by Colonial-Dev** [comment]
Grazie!

**Comment by leandrocp** [comment]
If that is not asking much, do you mind publishing a new version? Thanks!

**Comment by Colonial-Dev** [comment]
Of course - I'm away from my desktop, so it'll be a few minutes :p

**Comment by Colonial-Dev** [comment]
Version 0.10.1 pushed :partying_face:

**Comment by leandrocp** [comment]
> Version 0.10.1 pushed 🥳

thank you!

**Pull request merged**
