### PR TITLE
Update langs

### PR DESCRIPTION
**Pull request by leandrocp**
Updated a few langs:

- Elixir
- Erlang
- Gleam
- HEEx
- Lua
- CSS
- HTML
- Javascript
- Python
- Ruby
- SQL

Tried to update Rust as well but it failed loading so I'll leave for another day

### CODE REVIEW

**Comment by Colonial-Dev** [comment]
Ugh, looks like a merge conflict that GitHub doesn't feel like working with. Let me get you a patch file so you don't have to download everything again.

**Comment by leandrocp** [comment]
That's due to the other PR. I can fix it no worries :)

**Comment by leandrocp** [comment]
Those files were deleted in the other PR and update in this one. The resolution is deleting those 2 files

**Comment by Colonial-Dev** [comment]
Whoops, didn't catch that. These paths look too similar.

**Comment by Colonial-Dev** [comment]
Thanks again! I really should set up a reminder to update the languages every few months or so...

**Comment by Colonial-Dev** [comment]
v0.10.4 published!

**Comment by leandrocp** [comment]
> v0.10.4 published!

Thank you!

**Pull request merged**
